-- =====================================================
-- Supabase Keep-Alive System
-- Migration: Add heartbeat table and ping function
-- Purpose: Prevent database auto-pause on free tier
-- =====================================================

-- =====================================================
-- 1. Create keep_alive heartbeat table
-- =====================================================
CREATE TABLE IF NOT EXISTS public.keep_alive (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinged_at timestamptz DEFAULT now() NOT NULL,
    agent_info text,
    response_time_ms integer
);

-- Add comment for documentation
COMMENT ON TABLE public.keep_alive IS 'Heartbeat records to keep Supabase free tier database active';
COMMENT ON COLUMN public.keep_alive.pinged_at IS 'Timestamp when the ping was recorded';
COMMENT ON COLUMN public.keep_alive.agent_info IS 'Source of the ping (e.g., GitHub Actions, Manual)';
COMMENT ON COLUMN public.keep_alive.response_time_ms IS 'Optional response time in milliseconds';

-- =====================================================
-- 2. Enable RLS on keep_alive table
-- =====================================================
ALTER TABLE public.keep_alive ENABLE ROW LEVEL SECURITY;

-- Policy: Only service_role can access this table
-- This prevents unauthorized access while allowing GitHub Actions to ping
CREATE POLICY "Service role can manage keep_alive"
    ON public.keep_alive
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- =====================================================
-- 3. Create ping() RPC function
-- =====================================================
CREATE OR REPLACE FUNCTION ping(p_agent_info text DEFAULT 'Unknown')
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_start_time timestamptz;
    v_end_time timestamptz;
    v_response_time_ms integer;
    v_record_id bigint;
BEGIN
    -- Record start time
    v_start_time := clock_timestamp();

    -- Insert heartbeat record
    INSERT INTO public.keep_alive (agent_info)
    VALUES (p_agent_info)
    RETURNING id INTO v_record_id;

    -- Calculate response time
    v_end_time := clock_timestamp();
    v_response_time_ms := EXTRACT(MILLISECONDS FROM (v_end_time - v_start_time))::integer;

    -- Update the record with response time
    UPDATE public.keep_alive
    SET response_time_ms = v_response_time_ms
    WHERE id = v_record_id;

    -- Cleanup: Keep only the last 100 records
    DELETE FROM public.keep_alive
    WHERE id NOT IN (
        SELECT id FROM public.keep_alive
        ORDER BY pinged_at DESC
        LIMIT 100
    );

    -- Return success response
    RETURN jsonb_build_object(
        'success', true,
        'timestamp', now(),
        'response_time_ms', v_response_time_ms,
        'message', 'Database is alive',
        'record_id', v_record_id
    );
END;
$$;

-- Add comment for documentation
COMMENT ON FUNCTION ping(text) IS 'Heartbeat function to keep database active. Call via RPC to prevent auto-pause.';

-- =====================================================
-- 4. Create index for efficient cleanup queries
-- =====================================================
CREATE INDEX IF NOT EXISTS idx_keep_alive_pinged_at
    ON public.keep_alive (pinged_at DESC);

-- =====================================================
-- 5. Grant execute permission to authenticated and anon
-- (optional, for flexibility in calling methods)
-- =====================================================
GRANT EXECUTE ON FUNCTION ping(text) TO authenticated;
GRANT EXECUTE ON FUNCTION ping(text) TO anon;
GRANT EXECUTE ON FUNCTION ping(text) TO service_role;
